import 'package:get/get.dart';

class Translator extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'es_ES': {
          'error': 'Error',
          'logout_success': 'Sesión cerrada',
          'logout_message': 'Has cerrado sesión con éxito',
          'login': 'Iniciar Sesión',
          'sign_up': 'Registro',
          'email_label': 'Correo Electrónico',
          'password_label': 'Contraseña',
          'confirm_password_label': 'Confirmar Contraseña',
          'forgot_password': '¿Olvidaste tu contraseña?',
          'login_button': 'Iniciar Sesión',
          'sign_up_button': 'Registrarse',
          'have_account': '¿Ya tienes una cuenta?',
          'no_have_account': '¿No tienes una cuenta?',
          'sign_in_with_google': 'Iniciar Sesión con Google',
          'sign_up_with_google': 'Registrarse con Google',
          'email_required': 'El correo electrónico es requerido',
          'email_already_in_use': 'El correo electrónico ya está en uso',
          'password_required': 'La contraseña es requerida',
          'password_min_length':
              'La contraseña debe tener al menos 6 caracteres',
          'password_invalid':
              'La contraseña debe tener al menos dos letras mayúsculas, \ndos letras minúsculas y dos numeros',
          'password_easy': 'La contraseña es muy fácil',
          'email_invalid': 'El correo electrónico debe ser de google',
          'confirm_password_required':
              'La confirmación de la contraseña es requerida',
          'confirm_password_invalid':
              'La confirmación de la contraseña no coincide \ncon la contraseña',
          'unknown_error': 'Error desconocido',
          'wrong_password': 'Contraseña incorrecta',
          'user_not_found': 'Usuario no encontrado',
          'user_disabled': 'Usuario deshabilitado',
          'first_name_label': 'Primer nombre',
          'second_name_label': 'Segundo nombre',
          'last_name_label': 'Primer apellido',
          'second_last_name_label': 'Segundo apellido',
          'first_name_required': 'El primer nombre es requerido',
          'second_name_required': 'El segundo nombre es requerido',
          'last_name_required': 'El primer apellido es requerido',
          'second_last_name_required': 'El segundo apellido es requerido',
          'first_name_invalid': 'El primer nombre es invalido',
          'second_name_invalid': 'El segundo nombre es invalido',
          'last_name_invalid': 'El primer apellido es invalido',
          'second_last_name_invalid': 'El segundo apellido es invalido',
          'your_register_info_label': 'Su informacion de registro',
          'dni_label': 'Identificacion',
          'phone_label': 'Telefono',
        },
        'en_US': {
          'error': 'Error',
          'logout_success': 'Logout success',
          'logout_message': 'You have closed the session successfully',
          'login': 'Login',
          'sign_up': 'Sign Up',
          'email_label': 'Email',
          'password_label': 'Password',
          'confirm_password_label': 'Confirm Password',
          'forgot_password': 'Forgot Password?',
          'login_button': 'Login',
          'sign_up_button': 'Sign Up',
          'have_account': 'Already have an account?',
          'no_have_account': 'Don\'t have an account?',
          'sign_in_with_google': 'Sign in with Google',
          'sign_up_with_google': 'Sign up with Google',
          'email_required': 'Email is required',
          'email_already_in_use': 'Email already in use',
          'password_required': 'Password is required',
          'password_min_length': 'Password must have at least 6 characters',
          'password_invalid':
              'Password must have at least two uppercase letters, \ntwo lowercase letters and two numbers',
          'password_easy': 'Password is easy',
          'email_invalid': 'Email must be from google',
          'confirm_password_required': 'Confirm password is required',
          'confirm_password_invalid':
              'Confirm password does not match password',
          'unknown_error': 'Unknown error',
          'wrong_password': 'Wrong password',
          'user_not_found': 'User not found',
          'user_disabled': 'User disabled',
          'first_name_label': 'First name',
          'second_name_label': 'Second name',
          'last_name_label': 'Last name',
          'second_last_name_label': 'Second last name',
          'first_name_required': 'First name is required',
          'second_name_required': 'Second name is required',
          'last_name_required': 'Last name is required',
          'second_last_name_required': 'Second last name is required',
          'first_name_invalid': 'First name is invalid',
          'second_name_invalid': 'Second name is invalid',
          'last_name_invalid': 'Last name is invalid',
          'second_last_name_invalid': 'Second last name is invalid',
          'your_register_info_label': 'Your register-info',
          'dni_label': 'Identification',
          'phone_label': 'Phone',
        },
      };
}
