import 'package:get/get.dart';

class Translator extends Translations{
  @override
    Map<String, Map<String, String>> get keys => {
      'es_ES': {
        'error': 'Error',
        'logout_success': 'Sesión cerrada',
        'logout_message': 'Has cerrado sesión con éxito',
        'login': 'Iniciar Sesión',
        'sign_up': 'Registro',
        'email_label': 'Correo Electrónico',
        'password_label': 'Contraseña',
        'confirm_password_label': 'Confirmar Contraseña',
        'forgot_password': '¿Olvidaste tu contraseña?',
        'login_button': 'Iniciar Sesión',
        'sign_up_button': 'Registrarse',
        'have_account': '¿Ya tienes una cuenta?',
        'no_have_account': '¿No tienes una cuenta?',
        'sign_in_with_google': 'Iniciar Sesión con Google',
        'sign_up_with_google': 'Registrarse con Google',
        'email_required': 'El correo electrónico es requerido',
        'email_already_in_use': 'El correo electrónico ya está en uso',
        'password_required': 'La contraseña es requerida',
        'password_min_length': 'La contraseña debe tener al menos 6 caracteres',
        'password_invalid': 'La contraseña debe tener al menos dos letras mayúsculas, \ndos letras minúsculas y dos numeros',
        'password_easy': 'La contraseña es muy fácil',
        'email_invalid': 'El correo electrónico debe ser de google',
        'confirm_password_required': 'La confirmación de la contraseña es requerida',
        'confirm_password_invalid': 'La confirmación de la contraseña no coincide \ncon la contraseña',
        'unknown_error': 'Error desconocido',
        'wrong_password': 'Contraseña incorrecta',
        'user_not_found': 'Usuario no encontrado',
        'user_disabled': 'Usuario deshabilitado',
      },
      'en_US': {
        'error': 'Error',
        'logout_success': 'Logout success',
        'logout_message': 'You have closed the session successfully',
        'login': 'Login',
        'sign_up': 'Sign Up',
        'email_label': 'Email',
        'password_label': 'Password',
        'confirm_password_label': 'Confirm Password',
        'forgot_password': 'Forgot Password?',
        'login_button': 'Login',
        'sign_up_button': 'Sign Up',
        'have_account': 'Already have an account?',
        'no_have_account': 'Don\'t have an account?',
        'sign_in_with_google': 'Sign in with Google',
        'sign_up_with_google': 'Sign up with Google',
        'email_required': 'Email is required',
        'email_already_in_use': 'Email already in use',
        'password_required': 'Password is required',
        'password_min_length': 'Password must have at least 6 characters',
        'password_invalid': 'Password must have at least two uppercase letters, \ntwo lowercase letters and two numbers',
        'password_easy': 'Password is easy',
        'email_invalid': 'Email must be from google',
        'confirm_password_required': 'Confirm password is required',
        'confirm_password_invalid': 'Confirm password does not match password',
        'unknown_error': 'Unknown error',
        'wrong_password': 'Wrong password',
        'user_not_found': 'User not found',
        'user_disabled': 'User disabled',
      },
    };


}
